fields:
- metadata: {}
  name: ActualCost
  nullable: true
  type: double
- metadata: {}
  name: ActualEndDate
  nullable: true
  type: string
- metadata: {}
  name: ActualResourceHrs
  nullable: true
  type: double
- metadata: {}
  name: ActualStartDate
  nullable: true
  type: string
- metadata: {}
  name: LocationID
  nullable: true
  type: long
- metadata: {}
  name: ModifiedDate
  nullable: true
  type: string
- metadata: {}
  name: OperationSequence
  nullable: true
  type: long
- metadata: {}
  name: PlannedCost
  nullable: true
  type: double
- metadata: {}
  name: ProductID
  nullable: true
  type: long
- metadata: {}
  name: ScheduledEndDate
  nullable: true
  type: string
- metadata: {}
  name: ScheduledStartDate
  nullable: true
  type: string
- metadata: {}
  name: WorkOrderID
  nullable: true
  type: long
- metadata: {}
  name: _context_id
  nullable: false
  type: string
- metadata: {}
  name: _timeslice
  nullable: true
  type: timestamp
- metadata: {}
  name: _filepath_filename
  nullable: false
  type: string
- metadata: {}
  name: _corrupt_record
  nullable: true
  type: string
type: struct
