datalake: "/mnt/datalake/data"

engine:
  databricks:
    default_catalog: main
    logging_level: ERROR
    config:
      spark.master: local
      spark.databricks.delta.allowArbitraryProperties.enabled: true

pipeline_repo:
  pipeline_file:
    pipeline_root: "./config/{{project}}/pipelines"
    sql_root: "./config/{{project}}/sql"

spark_schema_repo:
  spark_schema_file:
    spark_schema_root: ./config/schema/spark

deltalake_schema_repo:
  deltalake_sql_file:
    deltalake_schema_root: ./config/schema

