dataflow:
  retries: 1
  retry_wait: 1
  enable_dataflow_types:
    - full_load
    - partition_load
    - merge_compare
    - merge_cdc
    - nuke 


  landing:
    cdc_customer:
      table:
        properties:
          yetl.lineagecolumn.loadtimestamp: _LOAD_TIMESTAMP
          yetl.lineagecolumn.timeslice: _TIMESLICE
          yetl.lineagecolumn.correlation_id: _CORRELATION_ID
          yetl.lineagecolumn.filename: _FILENAME
      path_date_format: "%Y%m"
      file_date_format: "%Y%m%d"
      format: csv
      path: data/landing/{{timeslice(path_date_format)}}/cdc_customer_{{timeslice(file_date_format)}}.csv
      read:
        auto: true
        options:
          mode: PERMISSIVE
          inferSchema: false
          header: true
          timestampFormat: yyyy-MM-dd HH:mm:ss
      exceptions:
          path: "data/delta_lake/exceptions"
          database: landing
          table: exceptions

  raw:
    cdc_customer:
      table:
        ddl: ./config/schema/deltalake
        properties:
          delta.appendOnly: false
          delta.checkpoint.writeStatsAsJson: true
          delta.compatibility.symlinkFormatManifest.enabled: false
          delta.dataSkippingNumIndexedCols: -1
          delta.logRetentionDuration: interval 30 days
          delta.deletedFileRetentionDuration: interval 1 week
          delta.enableChangeDataFeed: true
          delta.minReaderVersion: 1
          delta.minWriterVersion: 2
          delta.randomizeFilePrefixes: false
          delta.randomPrefixLength: 2

        # table constraints can be declared inline or via a SQL include file on the ddl
        check_constraints:
          amount_lower_bound: "amount > -1000"
          amount_upper_bound: "amount < 1000000"
      
      format: delta
      path: data/delta_lake/raw/cdc_customer
      write:
        mode: append
        options:
          mergeSchema: true
          
    cdc_customer_history:
      table:
        ddl: ./config/schema/deltalake
        properties:
          delta.appendOnly: false
          delta.checkpoint.writeStatsAsJson: true
          delta.compatibility.symlinkFormatManifest.enabled: false
          delta.dataSkippingNumIndexedCols: -1
          delta.logRetentionDuration: interval 30 days
          delta.deletedFileRetentionDuration: interval 1 week
          delta.enableChangeDataFeed: true
          delta.minReaderVersion: 1
          delta.minWriterVersion: 2
          delta.randomizeFilePrefixes: false
          delta.randomPrefixLength: 2

        # table constraints can be declared inline or via a SQL include file on the ddl
        check_constraints:
          amount_lower_bound: "amount > -1000"
          amount_upper_bound: "amount < 1000000"
      
      format: delta
      path: data/delta_lake/raw/cdc_customer_history
      write:
        mode: append
        options:
          mergeSchema: true