datalake: "{{cwd}}"
datalake_protocol: "file:"
spark:
  spark.master: local
  spark.databricks.delta.allowArbitraryProperties.enabled: true

spark_schema_repo:
  spark_schema_file:
    spark_schema_root: ./config/schema/spark

deltalake_schema_repo:
  deltalake_sql_file:
    deltalake_schema_root: ./config/schema/deltalake