database: demo
tables:
- enable_exceptions: true
  keys: []
  name: cdc_customer
- enable_exceptions: true
  keys: []
  name: customer_preferences
- enable_exceptions: true
  keys: []
  name: customer_details
