database: demo
tables:
- table: customer_preferences
  keys:
    - ID
- table: customer_details
  keys:
    - ID
  enable_exceptions: true
  thresholds:
    warning:
      min_rows: 1
      max_rows: 1000
      exception_count: 0
      exception_percent: 0
    error:
      min_rows: 0
      max_rows: 100000000
      exception_count: 50
      exception_percent: 80
