fields:
- metadata: {}
  name: id
  nullable: true
  type: integer
- metadata: {}
  name: allow_contact
  nullable: true
  type: boolean
- metadata: {}
  name: _corrupt_record
  nullable: true
  type: string
type: struct
