fields:
- metadata: {}
  name: id
  nullable: true
  type: string
- metadata: {}
  name: first_name
  nullable: true
  type: string
- metadata: {}
  name: last_name
  nullable: true
  type: string
- metadata: {}
  name: email
  nullable: true
  type: string
- metadata: {}
  name: gender
  nullable: true
  type: string
- metadata: {}
  name: job_title
  nullable: true
  type: string
- metadata: {}
  name: amount
  nullable: true
  type: double
type: struct
