dataflow:

  demo_landing:
    customer_details:
      type: Reader
      table:
        properties:
          yetl.schema.createIfNotExists: true
          yetl.metadata.timeslice: timeslice_file_date_format
          yetl.metadata.filepath_filename: true
      path_date_format: "%Y%m%d"
      file_date_format: "%Y%m%d"
      format: csv
      path: "landing/demo/{{timeslice_path_date_format}}/customer_details_{{timeslice_file_date_format}}.csv"
      read:
        auto: true
        options:
          mode: PERMISSIVE
          inferSchema: false
          header: true
      exceptions:
          path: "delta_lake/demo_landing/{{table_name}}_exceptions"
          database: demo_landing
          table: "{{table_name}}_exceptions"
      thresholds:
        warning:
          min_rows: 1
          max_rows: 1000
          exception_count: 0
          exception_percent: 0
        error:
          min_rows: 0
          max_rows: 100000000
          exception_count: 50
          exception_percent: 80

  demo_raw:
    customer_details:
      type: DeltaWriter
      table:

        partitioned_by:
          - _partition_key

        ddl: "{{ root }}"
        properties:
          yetl.metadata.dataset_id: true
          yetl.schema.createIfNotExists: true
          delta.appendOnly: false
          delta.checkpoint.writeStatsAsJson: true
          delta.autoOptimize.autoCompact: true  
          delta.autoOptimize.optimizeWrite: true 
          delta.compatibility.symlinkFormatManifest.enabled: false
          delta.dataSkippingNumIndexedCols: -1
          delta.logRetentionDuration: interval 30 days
          delta.deletedFileRetentionDuration: interval 1 week
          delta.enableChangeDataFeed: true
          delta.minReaderVersion: 1
          delta.minWriterVersion: 2
          delta.randomizeFilePrefixes: false
          delta.randomPrefixLength: 2
      
      format: delta
      path: delta_lake/demo_raw/customer_details
      write:
        mode: append
        options:
          mergeSchema: true