fields:
- metadata: {}
  name: AdditionalContactInfo
  nullable: true
  type: string
- metadata: {}
  name: BusinessEntityID
  nullable: true
  type: long
- metadata: {}
  name: Demographics
  nullable: true
  type: string
- metadata: {}
  name: EmailPromotion
  nullable: true
  type: long
- metadata: {}
  name: FirstName
  nullable: true
  type: string
- metadata: {}
  name: LastName
  nullable: true
  type: string
- metadata: {}
  name: MiddleName
  nullable: true
  type: string
- metadata: {}
  name: ModifiedDate
  nullable: true
  type: string
- metadata: {}
  name: NameStyle
  nullable: true
  type: boolean
- metadata: {}
  name: PersonType
  nullable: true
  type: string
- metadata: {}
  name: Suffix
  nullable: true
  type: string
- metadata: {}
  name: Title
  nullable: true
  type: string
- metadata: {}
  name: rowguid
  nullable: true
  type: string
- metadata: {}
  name: _context_id
  nullable: false
  type: string
- metadata: {}
  name: _timeslice
  nullable: true
  type: timestamp
- metadata: {}
  name: _filepath_filename
  nullable: false
  type: string
- metadata: {}
  name: _corrupt_record
  nullable: true
  type: string
type: struct
