fields:
- metadata: {}
  name: AddressID
  nullable: true
  type: long
- metadata: {}
  name: AddressLine1
  nullable: true
  type: string
- metadata: {}
  name: AddressLine2
  nullable: true
  type: string
- metadata: {}
  name: City
  nullable: true
  type: string
- metadata: {}
  name: ModifiedDate
  nullable: true
  type: string
- metadata: {}
  name: PostalCode
  nullable: true
  type: string
- metadata: {}
  name: SpatialLocation
  nullable: true
  type: string
- metadata: {}
  name: StateProvinceID
  nullable: true
  type: long
- metadata: {}
  name: rowguid
  nullable: true
  type: string
- metadata: {}
  name: _context_id
  nullable: false
  type: string
- metadata: {}
  name: _timeslice
  nullable: true
  type: timestamp
- metadata: {}
  name: _filepath_filename
  nullable: false
  type: string
- metadata: {}
  name: _corrupt_record
  nullable: true
  type: string
type: struct
