fields:
- metadata: {}
  name: ChangeNumber
  nullable: true
  type: long
- metadata: {}
  name: Document
  nullable: true
  type: string
- metadata: {}
  name: DocumentLevel
  nullable: true
  type: long
- metadata: {}
  name: DocumentNode
  nullable: true
  type: string
- metadata: {}
  name: DocumentSummary
  nullable: true
  type: string
- metadata: {}
  name: FileExtension
  nullable: true
  type: string
- metadata: {}
  name: FileName
  nullable: true
  type: string
- metadata: {}
  name: FolderFlag
  nullable: true
  type: boolean
- metadata: {}
  name: ModifiedDate
  nullable: true
  type: string
- metadata: {}
  name: Owner
  nullable: true
  type: long
- metadata: {}
  name: Revision
  nullable: true
  type: string
- metadata: {}
  name: Status
  nullable: true
  type: long
- metadata: {}
  name: Title
  nullable: true
  type: string
- metadata: {}
  name: rowguid
  nullable: true
  type: string
- metadata: {}
  name: _context_id
  nullable: false
  type: string
- metadata: {}
  name: _timeslice
  nullable: true
  type: timestamp
- metadata: {}
  name: _filepath_filename
  nullable: false
  type: string
- metadata: {}
  name: _corrupt_record
  nullable: true
  type: string
type: struct
