fields:
- metadata: {}
  name: Bin
  nullable: true
  type: long
- metadata: {}
  name: LocationID
  nullable: true
  type: long
- metadata: {}
  name: ModifiedDate
  nullable: true
  type: string
- metadata: {}
  name: ProductID
  nullable: true
  type: long
- metadata: {}
  name: Quantity
  nullable: true
  type: long
- metadata: {}
  name: Shelf
  nullable: true
  type: string
- metadata: {}
  name: rowguid
  nullable: true
  type: string
- metadata: {}
  name: _context_id
  nullable: false
  type: string
- metadata: {}
  name: _timeslice
  nullable: true
  type: timestamp
- metadata: {}
  name: _filepath_filename
  nullable: false
  type: string
- metadata: {}
  name: _corrupt_record
  nullable: true
  type: string
type: struct
