fields:
- metadata: {}
  name: EmployeeID
  nullable: true
  type: long
- metadata: {}
  name: Freight
  nullable: true
  type: double
- metadata: {}
  name: ModifiedDate
  nullable: true
  type: string
- metadata: {}
  name: OrderDate
  nullable: true
  type: string
- metadata: {}
  name: PurchaseOrderID
  nullable: true
  type: long
- metadata: {}
  name: RevisionNumber
  nullable: true
  type: long
- metadata: {}
  name: ShipDate
  nullable: true
  type: string
- metadata: {}
  name: ShipMethodID
  nullable: true
  type: long
- metadata: {}
  name: Status
  nullable: true
  type: long
- metadata: {}
  name: SubTotal
  nullable: true
  type: double
- metadata: {}
  name: TaxAmt
  nullable: true
  type: double
- metadata: {}
  name: TotalDue
  nullable: true
  type: double
- metadata: {}
  name: VendorID
  nullable: true
  type: long
- metadata: {}
  name: _context_id
  nullable: false
  type: string
- metadata: {}
  name: _timeslice
  nullable: true
  type: timestamp
- metadata: {}
  name: _filepath_filename
  nullable: false
  type: string
- metadata: {}
  name: _corrupt_record
  nullable: true
  type: string
type: struct
