fields:
- metadata: {}
  name: DueDate
  nullable: true
  type: string
- metadata: {}
  name: LineTotal
  nullable: true
  type: double
- metadata: {}
  name: ModifiedDate
  nullable: true
  type: string
- metadata: {}
  name: OrderQty
  nullable: true
  type: long
- metadata: {}
  name: ProductID
  nullable: true
  type: long
- metadata: {}
  name: PurchaseOrderDetailID
  nullable: true
  type: long
- metadata: {}
  name: PurchaseOrderID
  nullable: true
  type: long
- metadata: {}
  name: ReceivedQty
  nullable: true
  type: double
- metadata: {}
  name: RejectedQty
  nullable: true
  type: double
- metadata: {}
  name: StockedQty
  nullable: true
  type: double
- metadata: {}
  name: UnitPrice
  nullable: true
  type: double
- metadata: {}
  name: _context_id
  nullable: false
  type: string
- metadata: {}
  name: _timeslice
  nullable: true
  type: timestamp
- metadata: {}
  name: _filepath_filename
  nullable: false
  type: string
- metadata: {}
  name: _corrupt_record
  nullable: true
  type: string
type: struct
