fields:
- metadata: {}
  name: BusinessEntityID
  nullable: true
  type: long
- metadata: {}
  name: Demographics
  nullable: true
  type: string
- metadata: {}
  name: ModifiedDate
  nullable: true
  type: string
- metadata: {}
  name: Name
  nullable: true
  type: string
- metadata: {}
  name: SalesPersonID
  nullable: true
  type: long
- metadata: {}
  name: rowguid
  nullable: true
  type: string
- metadata: {}
  name: _context_id
  nullable: false
  type: string
- metadata: {}
  name: _timeslice
  nullable: true
  type: timestamp
- metadata: {}
  name: _filepath_filename
  nullable: false
  type: string
- metadata: {}
  name: _corrupt_record
  nullable: true
  type: string
type: struct
