fields:
- metadata: {}
  name: CarrierTrackingNumber
  nullable: true
  type: string
- metadata: {}
  name: LineTotal
  nullable: true
  type: double
- metadata: {}
  name: ModifiedDate
  nullable: true
  type: string
- metadata: {}
  name: OrderQty
  nullable: true
  type: long
- metadata: {}
  name: ProductID
  nullable: true
  type: long
- metadata: {}
  name: SalesOrderDetailID
  nullable: true
  type: long
- metadata: {}
  name: SalesOrderID
  nullable: true
  type: long
- metadata: {}
  name: SpecialOfferID
  nullable: true
  type: long
- metadata: {}
  name: UnitPrice
  nullable: true
  type: double
- metadata: {}
  name: UnitPriceDiscount
  nullable: true
  type: double
- metadata: {}
  name: rowguid
  nullable: true
  type: string
- metadata: {}
  name: _context_id
  nullable: false
  type: string
- metadata: {}
  name: _timeslice
  nullable: true
  type: timestamp
- metadata: {}
  name: _filepath_filename
  nullable: false
  type: string
- metadata: {}
  name: _corrupt_record
  nullable: true
  type: string
type: struct
