fields:
- metadata: {}
  name: Bonus
  nullable: true
  type: double
- metadata: {}
  name: BusinessEntityID
  nullable: true
  type: long
- metadata: {}
  name: CommissionPct
  nullable: true
  type: double
- metadata: {}
  name: ModifiedDate
  nullable: true
  type: string
- metadata: {}
  name: SalesLastYear
  nullable: true
  type: double
- metadata: {}
  name: SalesQuota
  nullable: true
  type: double
- metadata: {}
  name: SalesYTD
  nullable: true
  type: double
- metadata: {}
  name: TerritoryID
  nullable: true
  type: long
- metadata: {}
  name: rowguid
  nullable: true
  type: string
- metadata: {}
  name: _context_id
  nullable: false
  type: string
- metadata: {}
  name: _timeslice
  nullable: true
  type: timestamp
- metadata: {}
  name: _filepath_filename
  nullable: false
  type: string
- metadata: {}
  name: _corrupt_record
  nullable: true
  type: string
type: struct
