fields:
- metadata: {}
  name: ModifiedDate
  nullable: true
  type: string
- metadata: {}
  name: Primary
  nullable: true
  type: boolean
- metadata: {}
  name: ProductID
  nullable: true
  type: long
- metadata: {}
  name: ProductPhotoID
  nullable: true
  type: long
- metadata: {}
  name: _context_id
  nullable: false
  type: string
- metadata: {}
  name: _timeslice
  nullable: true
  type: timestamp
- metadata: {}
  name: _filepath_filename
  nullable: false
  type: string
- metadata: {}
  name: _corrupt_record
  nullable: true
  type: string
type: struct
